version: '3'
services:
  nginx:
    container_name: todo-app-nginx
    image: nginx:1.17.10-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/public/static:/app/public/static
  app:
    container_name: todo-app-php
    build: .
    ports:
      - "9000:9000"
    volumes:
      - ./app:/app
    environment:
      DB_NAME: todo
      DB_USER: todo_user
      DB_PASS: todo_pass
      DB_HOST: db
      # LOGO_IMG: 
  db:
    container_name: todo-app-db
    image: mysql:8.0.19
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass